# Generated by Django 2.2.24 on 2021-09-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210921_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
