# Generated by Django 2.2.24 on 2021-09-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210922_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurb',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
